### ISSUE TITLE
Make reverse scroll bring the last application

### ISSUE THREAD

**Issue by mystiquewolf** [sunwxg/gnome-shell-extension-panelScroll#1]
Such a nice extension. Thank you very much!

Is it possible to make the scroll up bring the last application that was switched from scroll down.

Say i have Firefox focused, also Terminal and Nautilus files on background. I scroll down and Nautilus is shown. Now If i scroll up i would prefer that Firefox is brought to focus again. Instead it will 1st focus Terminal and only on next scroll up Firefox.

**Comment by sunwxg** [comment]
I understand what you need, that's also I want to do at beginning. But I don't find a proper list of windows in  the system. If we do like what you say, that means I need to maintain a windows list myself, add quite a few codes in extensions. If I have enough time, I will do it.
