### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by AlexWayfer** [sunwxg/gnome-shell-extension-panelScroll#3]
Hello.

Thank you for this extension and supporting GNOME 40.

I'm interested in switching workspaces by a scroll on both sides of top bar, left and right.

So, I think, it'd be nice to have minimal configuration window where you can change scroll actions, for example "Left side" and "Right side" with drop-downs and 2 options: "Switch windows" and "Switch workspaces".

**Comment by sunwxg** [comment]
Thanks for the suggestion. Add it in the future.
